apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: skaffold-example
build:
  artifacts:
    - image: skaffold-example
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - manifest/kube.yaml
